### ISSUE TITLE
Cannot build for bionic/focal ARM64

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion-packaging#18]
```
# apt-get install debhelper debhelper-compat
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'debhelper' instead of 'debhelper-compat'
debhelper is already the newest version (12.10ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

```
dpkg-buildpackage: info: source package motion
dpkg-buildpackage: info: source version 4.5.1-1
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by Motion-Project <tosiara@users.noreply.github.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture arm64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 13) debhelper-compat (= 13)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

**Comment by tosiara** [comment]
older dc1785f50c6fd8f54e656cd2173c07017343e205 revision builds fine

**Comment by Mr-Dave** [comment]
Yea, build with that for now.  

It is caused by MMAL and upstream including it but it isn't functional for 64bit.  The revision in 4.5.1 should do a better job checking for a functional version.   

(I don't want to revert this yet in production and am thinking of trying to find a different method so that the script will work with all prior Motion versions and arm64 distros.)

**Comment by DiagnozHub** [comment]
Its bad, I wanna try "focal ARM64" on my device (

**Comment by tosiara** [comment]
Uploaded. You can try it now
https://github.com/Motion-Project/motion/releases/tag/release-4.5.1

**Comment by DiagnozHub** [comment]
Thanks a lot ))))))
I installed app, will test it.
