### ISSUE TITLE
Raspbian permissions

### ISSUE THREAD

**Issue by ghost** [Motion-Project/motion-packaging#2]
- v4.0
- raspbian stretch
- standalone
- hardware [x86, ARM, other]: pi3
- operating system [Linux (which), FreeBSD, other]: raspbian

Motion creates files with inconvenient permissions and there is no config setting to change this.
It is `motion:motion` with `rw_r__r__`

This seems to be an old issue:
https://github.com/Motion-Project/motion/issues/35

**Comment by johnelliott** [comment]
I am interested in finding out what permissions should be for running 4.0.1 installed via Apt on raspbian stretch. I'd like to run with `(sudo) systemctl start motion`. To date I've been unable to determine what configuration leads to the camera running and web service being up. I had one machine working but in the process of trying to determine what was working I broke it. 🤷‍♂️ 

Once I figure this out I'll update my Ansible deploy scripts for the pi and share them, but I can't seem to find what the necessary permissions are to run with systemd.

**Comment by Mr-Dave** [comment]
Well, the first item is that you should make sure to not run Motion as `sudo` it should be run as a "harmless user" since it has functionality to run scripts and we wouldn't want those run as the sudo user.  

Next, while some may feel that the permissions are "inconvenient" they are critical to maintaining the integrity of your system.  The Motion application can not and should not be going around changing your permissions.  Only you can determine the level of security (or insecurity) that you want to have on your system.  

By default, configuration files install in the `/etc` directory which dictates certain permissions to modify.  The application can also read from the home directory or even take as a command line parameter the location to suit your needs.  

If Rasbian is protecting devices such as cameras from users being able to open them, I'd say again that Motion should not be just automatically adjusting permissions.  They were put in place for a reason and only you can decide whether to open them up to applications.  Likewise for syslogs or directories for the PIDs which may default to one location which isn't permitted on your system but can be changed to log elsewhere via the configuration file.

**Comment by johnelliott** [comment]
Thank you for your response. I did some general reading about users and groups to get more familiar, but even with better understanding I wasn't able to get anything running, so I took a step back to see what the options were. In the end my permissions were sometimes correct, but the real problem was how the program started up.

I looked at the systemd unit file and saw it was generated from the old init system, so I read [motion.init](https://github.com/Motion-Project/motion-packaging/blob/master/debian/motion.init) and saw that the `start_motion_daemon` was required 🤔. 

That detail was why I never saw a motion pid. Typically when I am making systemd units for programs that don't ship with them I will skip whatever self-deamonizing code a lib ships with and use systemd to restart the process and send the errors to the systemd journal. In this case the provided services needed that sort of boolean set to true.

Since the included init scripts didn't seem to be working for restarting and reloading. I searched around the installed files and saw this: https://github.com/Motion-Project/motion/blob/master/motion.service.in. Once I saw that maybe someone thought that was a decent idea, I wrote a similar unit file and skipped the included unit files. This was much more like what I was used to and it worked perfectly:

```
[Unit]
Description=my motion daemon
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/motion -n
User=motion
PIDFile=/var/run/motion.pid
RestartSec=5

[Install]
WantedBy=multi-user.target
```

@Mr-Dave I am just curious about what the current way to make motion a service is, and whether I've done something bad by making my own init file, and whether work remains update the existing service-running code.

I think the issue here is that the intent of the motion developers isn't clear to the users. Perhaps we could add some documentation about understanding permissions or choosing a way to run the program.

Over-all I'm very pleased with motion 😊

**Comment by Mr-Dave** [comment]
Well, the intent is of course to make it all "just work" on all the systems.  The problem is the amount of time I've spent looking at this (virtually none) as well as the fact that (as I understand it), the method of starting the service has changed in the base systems over time.  From service to systemctl.  

This is of course compounded by the number of operating systems supported.  Ubuntu 14.04 to present, the last two Debian as well as the last two Raspbian.  Multiplied then by the number of architectures.  (Look at all the debs for the 4.1.1 release)

In general, I REALLY shy away from changing any permissions because that could have bad consequences.    I'm open to documentation revisions (the build instructions are included with the code) as well as PR either for debian rules, packaging scripts or initialization scripts.

**Comment by adjenks** [comment]
I would like written files to have the permission 770 so they can be read and written by the group but not random users. How do I do this without having a small window of time where they are accessible to anyone? I was hoping the configuration would allow me to set "file_creation_chmod" or something like that. I see multiple requests for this feature in the issues but they have all been closed. 

It's not ideal because there is a theoretical fraction of a second where the file exists with the wrong permissions, but for now, I will just do this in the config:
`on_movie_end chmod 770 %f`

**Comment by tosiara** [comment]
Can you try `umask` as described in this ticket? https://github.com/Motion-Project/motion/issues/1297
