### ISSUE TITLE
Debian trixie support - ./builddeb.sh: 125: [: Illegal number: n/a

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion-packaging#23]
```
# ./builddeb.sh a a 4.7

Using Username: a, User Email: a, Git Branch: 4.7, Install Pkgs: N, Arch: x86_64, PKGARCH: amd64

./builddeb.sh: 125: [: Illegal number: n/a
./builddeb.sh: 127: [: Illegal number: n/a
./builddeb.sh: 141: [: Illegal number: n/a
The following packages need to be installed with the following command: sudo apt-get install  libmysqlclient-dev

root@f5a87fd20af0:/debs/motion-packaging# apt-get install  libmysqlclient-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb-dev-compat libmariadb-dev

E: Package 'libmysqlclient-dev' has no installation candidate
root@f5a87fd20af0:/debs/motion-packaging# apt-get install  libmariadb-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libmariadb-dev is already the newest version (1:11.4.2-4).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
```

**Comment by tosiara** [comment]
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie
```

**Comment by Mr-Dave** [comment]
Sid is not supported by the script for automatic deb creation.  The packages change constantly as new versions are created, the packages that are included are in "testing", etc., etc.

**Comment by tosiara** [comment]
For my automated build I have fixed it so far this way:
https://github.com/Motion-Project/motion-packaging/commit/fe2634a4551edef9366c3cec911836aeab6d13fa

Let me know if you want the same, I will send a PR

**Comment by Mr-Dave** [comment]
No PR.  The problem isn't really with just doing that line.  It is the remainder of the script is dependent upon the version to determine what to do.  It is just "luck" that none of the names of the dependencies or standards requirements has changed "yet" and the last one worked.     

We've been doing this for 8 years and we've needed 5 different Debian packaging rules.  Just nine months ago libcamera changed some names.  They could just as likely do it again tomorrow and roll it into Sid.  At that point not only would the script fail but months down the road the any posted Motion deb that used the old packages would fail.  

I do however want to thank you for creating all the release debs.  I'd also note that this annual release was pushed out early so that it could potentially make its way into Trixie.   If it makes it, it will mean that it is the last set for quite a while.
